import { useState } from 'react';

const SECTIONS = [
  {
    id: 'verdicts',
    label: 'VERDICTS & SCORES',
    icon: '◈',
    entries: [
      {
        term: 'Bullish',
        short: 'The system thinks the stock is likely to go up.',
        detail: 'More positive signals than negative. The agent found evidence — from price movement, news, or technicals — that the stock has upward momentum or is undervalued right now.',
      },
      {
        term: 'Bearish',
        short: 'The system thinks the stock may go down.',
        detail: 'More negative signals than positive. Could mean the stock is overpriced, losing momentum, or surrounded by bad news.',
      },
      {
        term: 'Neutral',
        short: 'No clear direction. Signals are mixed or data is thin.',
        detail: 'The agent couldn\'t build a confident case in either direction. This can happen when signals disagree with each other or when key data sources were unavailable.',
      },
      {
        term: 'Bull Case Score',
        short: 'How strong the "buy" argument is, out of 100.',
        detail: 'Computed purely from data — not generated by the AI. 80+ means strong bullish evidence. 50 means no clear view. 20 means weak bull case. It\'s capped when signals conflict, so a score of 75+ means the evidence genuinely agrees.',
      },
      {
        term: 'Model Confidence',
        short: 'How certain the system is in its own reading.',
        detail: 'Different from the bull score. A brief can be bullish with low confidence — meaning "the signals say buy, but data was stale or sources disagreed on other things." Low confidence = treat the verdict with more skepticism.',
      },
      {
        term: 'Agent Bias Verdict',
        short: 'The system\'s bottom-line call after weighing everything.',
        detail: 'Ranges from STRONGLY BULLISH → MILDLY BULLISH → NEUTRAL → MILDLY BEARISH → STRONGLY BEARISH. "Strongly" means signals aligned cleanly. "Mildly" means there\'s friction — some evidence cut the other way.',
      },
    ],
  },
  {
    id: 'technicals',
    label: 'TECHNICAL INDICATORS',
    icon: '⚏',
    entries: [
      {
        term: 'RSI (Relative Strength Index)',
        short: 'Measures how "tired" or "energised" a stock\'s recent price moves are.',
        detail: 'Scale of 0–100. Above 70 = "overbought" — the stock has been bought heavily and may be due for a pullback. Below 30 = "oversold" — it\'s been sold hard and might bounce. Between 30–70 is considered normal territory.',
      },
      {
        term: 'MACD',
        short: 'Shows whether a stock\'s momentum is building or fading.',
        detail: 'Stands for Moving Average Convergence Divergence. When it crosses above zero (bullish crossover), upward momentum is accelerating. Below zero (bearish crossover) means momentum is fading. Think of it as a speedometer for price direction.',
      },
      {
        term: 'MA 50 (50-day Moving Average)',
        short: 'The average closing price over the last 50 trading days.',
        detail: 'If the current price is above the MA 50, the stock is in a short-to-medium term uptrend. Traders watch this as a support or resistance level. A price crossing the MA 50 can signal a trend change.',
      },
      {
        term: 'MA 200 (200-day Moving Average)',
        short: 'The average closing price over the last 200 trading days.',
        detail: 'The big picture health check. Above the MA 200 = the stock is in a long-term uptrend. Below it = long-term downtrend. This is one of the most widely watched lines in professional finance.',
      },
      {
        term: 'Bollinger Bands',
        short: 'Price boundaries that show whether a stock is stretched or compressed.',
        detail: 'Three lines: a middle average and upper/lower boundaries. When price touches the upper band, it may be overextended. When it touches the lower band, it may be oversold. The bands also widen during volatile periods and tighten during calm ones.',
      },
    ],
  },
  {
    id: 'sources',
    label: 'DATA SOURCES',
    icon: '◎',
    entries: [
      {
        term: 'SEC Filing (MD&A)',
        short: 'The company\'s own words about how its business is doing.',
        detail: 'Every US public company must file regular reports with the SEC (the US financial regulator). The MD&A — Management Discussion & Analysis — is the section where executives explain what happened, what risks they see, and where the business is going. It\'s unfiltered from the company itself.',
      },
      {
        term: 'News Sentiment',
        short: 'Whether recent news about this stock is positive, negative, or neutral.',
        detail: 'The system reads recent headlines via Tavily and runs them through FinBERT — an AI model trained specifically on financial language. It scores each article and aggregates them. Unlike general sentiment AI, FinBERT understands that "stock falls on earnings beat" is actually nuanced.',
      },
      {
        term: 'Price Data (yfinance)',
        short: 'Historical trading prices pulled from Yahoo Finance.',
        detail: 'The raw opening, closing, high, and low prices for each trading day. Used to compute the technical indicators (RSI, MACD, moving averages) and to track price trends over the analysis window.',
      },
      {
        term: 'AVAILABLE / CACHED / UNAVAILABLE',
        short: 'Whether each data source returned fresh, stored, or no data.',
        detail: 'AVAILABLE = fetched live right now. CACHED = retrieved from a recent save (data may be hours or days old — the confidence score is penalised for this). UNAVAILABLE = the source failed entirely. The brief still generates from whatever sources did respond.',
      },
      {
        term: 'Vector Store (ChromaDB)',
        short: 'A memory bank of past documents the system can search.',
        detail: 'When the system fetches news or SEC filings, it saves them in a local database. If a live fetch fails next time, it can fall back to the stored version. It also enables semantic search — finding relevant past research even if the exact words don\'t match.',
      },
    ],
  },
  {
    id: 'signals',
    label: 'SIGNALS & CONFLICTS',
    icon: '⚑',
    entries: [
      {
        term: 'Signal',
        short: 'One piece of evidence pointing in a direction.',
        detail: 'Examples: "RSI oversold" is a bullish signal. "MACD bearish crossover" is a bearish signal. "Bullish news sentiment" is a bullish signal. The system collects all signals and weighs them together to produce the verdict.',
      },
      {
        term: 'Signal Conflict',
        short: 'Two sources are pointing in opposite directions.',
        detail: 'Example: News is positive about the company, but the RSI says the stock is already overbought. Or the technical trend is up, but the SEC filing mentions revenue headwinds. FinSight surfaces these instead of silently averaging them away — conflicts are useful information.',
      },
      {
        term: 'Cross-Validation Clear',
        short: 'All signals agree. No contradictions detected.',
        detail: 'The green state — every data source is pointing the same direction. This doesn\'t guarantee the verdict is right, but it does mean the system\'s reading is internally consistent.',
      },
      {
        term: 'Parabolic Velocity',
        short: 'The stock has moved very fast in a short time.',
        detail: 'When a stock rises or falls more than ~8% quickly, that\'s flagged as a conflict because fast moves are often followed by reversals. The system is warning you: "the momentum is real, but so is the risk of a snapback."',
      },
    ],
  },
  {
    id: 'eval',
    label: 'ACCURACY TRACKING',
    icon: '◉',
    entries: [
      {
        term: 'Eval Layer',
        short: 'The system tracks whether its own predictions were right.',
        detail: 'Every brief is logged. 5 trading days after it\'s generated, the system checks if the stock moved at least 1% in the predicted direction. This creates an honest track record — the leaderboard shows accuracy per ticker over time.',
      },
      {
        term: 'Signal Correct / Incorrect',
        short: 'Did the verdict match what the stock actually did?',
        detail: 'A bullish brief is "correct" if the price rose ≥1% within 5 trading days. Bearish = price fell ≥1%. Neutral = harder to evaluate, so it\'s typically skipped. The 1% threshold filters out noise.',
      },
    ],
  },
];

export default function HelpModal({ onClose }) {
  const [activeSection, setActiveSection] = useState('verdicts');
  const [expanded, setExpanded] = useState(null);

  const section = SECTIONS.find(s => s.id === activeSection);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content"
        onClick={e => e.stopPropagation()}
        style={{ maxWidth: '680px', width: '90vw', maxHeight: '80vh', display: 'flex', flexDirection: 'column' }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px', flexShrink: 0 }}>
          <div>
            <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--accent-amber)', fontSize: '16px', letterSpacing: '2px', marginBottom: '4px' }}>
              PLAIN ENGLISH GUIDE
            </h2>
            <div style={{ color: 'var(--text-muted)', fontSize: '10px', letterSpacing: '1px' }}>
              NEW TO FINANCE? START HERE.
            </div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: '18px', lineHeight: 1 }}>✕</button>
        </div>

        {/* Section tabs */}
        <div style={{ display: 'flex', gap: '4px', marginBottom: '20px', flexWrap: 'wrap', flexShrink: 0 }}>
          {SECTIONS.map(s => (
            <button
              key={s.id}
              onClick={() => { setActiveSection(s.id); setExpanded(null); }}
              style={{
                background: activeSection === s.id ? 'rgba(255,165,0,0.1)' : 'transparent',
                border: `1px solid ${activeSection === s.id ? 'var(--accent-amber)' : 'var(--border)'}`,
                color: activeSection === s.id ? 'var(--accent-amber)' : 'var(--text-muted)',
                fontSize: '9px',
                letterSpacing: '1px',
                padding: '5px 10px',
                cursor: 'pointer',
                fontFamily: 'var(--font-mono)',
                display: 'flex',
                alignItems: 'center',
                gap: '5px',
              }}
            >
              <span>{s.icon}</span> {s.label}
            </button>
          ))}
        </div>

        {/* Entries */}
        <div style={{ overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '2px' }}>
          {section.entries.map((entry, i) => (
            <div
              key={i}
              onClick={() => setExpanded(expanded === i ? null : i)}
              style={{
                border: '1px solid var(--border)',
                borderLeft: `2px solid ${expanded === i ? 'var(--accent-amber)' : 'var(--border)'}`,
                backgroundColor: expanded === i ? 'rgba(255,165,0,0.03)' : 'rgba(255,255,255,0.01)',
                padding: '12px 16px',
                cursor: 'pointer',
                transition: 'all 0.15s',
              }}
              onMouseEnter={e => { if (expanded !== i) e.currentTarget.style.borderLeftColor = 'rgba(255,165,0,0.3)'; }}
              onMouseLeave={e => { if (expanded !== i) e.currentTarget.style.borderLeftColor = 'var(--border)'; }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '12px' }}>
                <div style={{ flex: 1 }}>
                  <div style={{
                    color: expanded === i ? 'var(--accent-amber)' : 'var(--text-primary)',
                    fontSize: '12px',
                    fontWeight: 'bold',
                    letterSpacing: '0.5px',
                    marginBottom: '3px',
                    fontFamily: 'var(--font-mono)',
                    textTransform: 'uppercase',
                  }}>
                    {entry.term}
                  </div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '11px', lineHeight: 1.5 }}>
                    {entry.short}
                  </div>
                  {expanded === i && (
                    <div style={{
                      marginTop: '10px',
                      paddingTop: '10px',
                      borderTop: '1px solid rgba(255,255,255,0.06)',
                      color: 'var(--text-primary)',
                      fontSize: '12px',
                      lineHeight: 1.7,
                    }}>
                      {entry.detail}
                    </div>
                  )}
                </div>
                <span style={{ color: 'var(--text-muted)', fontSize: '10px', flexShrink: 0, marginTop: '2px' }}>
                  {expanded === i ? '▲' : '▼'}
                </span>
              </div>
            </div>
          ))}
        </div>

        <div style={{ marginTop: '20px', paddingTop: '16px', borderTop: '1px solid var(--border)', flexShrink: 0 }}>
          <div style={{ fontSize: '9px', color: 'var(--text-muted)', letterSpacing: '1px', textAlign: 'center' }}>
            HOVER OVER ANY <span style={{ color: 'var(--accent-amber)' }}>?</span> IN THE DASHBOARD FOR IN-CONTEXT EXPLANATIONS
          </div>
        </div>
      </div>
    </div>
  );
}
