export function generateMarkdown(brief) {
  const date = new Date(brief.created_at * 1000).toISOString().split('T')[0];
  const data = brief.brief_data;
  
  let md = `# FinSight Analysis Report — ${brief.ticker}\n`;
  md += `**Date**: ${date} | **Confidence**: ${Math.round(brief.confidence * 100)}% | **Verdict**: ${brief.net_signal.toUpperCase()}\n\n`;
  
  md += `## Executive Summary\n`;
  md += `${data.brief_text || 'No summary available.'}\n\n`;
  
  md += `## Bull Case\n`;
  if (data.bull_signals?.length > 0) {
    data.bull_signals.forEach(s => {
      md += `- ${s.text} [${s.source?.toUpperCase() || 'AGENT'}]\n`;
    });
  } else {
    md += `No significant bull signals detected.\n`;
  }
  md += `\n`;
  
  md += `## Bear Case\n`;
  if (data.bear_signals?.length > 0) {
    data.bear_signals.forEach(s => {
      md += `- ${s.text} [${s.source?.toUpperCase() || 'AGENT'}]\n`;
    });
  } else {
    md += `No significant bear signals detected.\n`;
  }
  md += `\n`;
  
  if (data.conflicts?.length > 0) {
    md += `## Signal Conflicts\n`;
    data.conflicts.forEach(c => {
      md += `⚠ ${c}\n`;
    });
    md += `\n`;
  }
  
  md += `---\n`;
  md += `*Generated by FinSight Sovereign Terminal | Latency: ${data.total_latency_ms}ms*\n`;
  
  return md;
}

export function downloadFile(content, filename, contentType) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
